"""
build_notebook_lab2.py
======================
Tạo file Lab2_2251172268.ipynb – chạy: python build_notebook_lab2.py
"""
import json, os

NB = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                  "Lab2_2251172268.ipynb")

def md(*lines):
    return {"cell_type": "markdown", "metadata": {}, "source": list(lines)}

def code(*lines, outputs=None):
    return {"cell_type": "code", "execution_count": None,
            "metadata": {}, "outputs": outputs or [],
            "source": list(lines)}

C = []

# ── TIÊU ĐỀ ──────────────────────────────────────────────
C.append(md(
"# CSE457 – Xử lý âm thanh và tiếng nói\n",
"## LAB 2: Đặc trưng tiếng nói và nhận dạng bằng DTW\n",
"### Từ phân tích ngắn hạn đến MFCC, căn chỉnh thời gian động và nhận dạng từ đơn\n",
"---\n",
"| Thông tin | Nội dung |\n",
"|-----------|----------|\n",
"| **Sinh viên** | Dương Tiến Đạt |\n",
"| **MSSV** | 2251172268 |\n",
"| **Học phần** | CSE457 – Xử lý âm thanh và tiếng nói |\n",
"| **Vocabulary** | Không, Một, Hai, Ba, Bốn (5 từ × 5 lần = 25 file WAV) |\n",
"\n",
"**Pipeline:**\n",
"```\n",
"Audio WAV → Endpoint Detection → Framing+Hamming → MFCC → DTW với templates → Từ được nhận dạng\n",
"```\n",
"\n",
"> Notebook này chạy **hoàn toàn tự động** từ đầu đến cuối.  \n",
"> Không phụ thuộc biến đã chạy thủ công.\n",
))

# ── SETUP ────────────────────────────────────────────────
C.append(md("## 0. Cài đặt và import"))
C.append(code(
"import subprocess, sys\n",
"pkgs = ['numpy','scipy','matplotlib','scikit-learn']\n",
"for p in pkgs:\n",
"    try: __import__(p.replace('-','_'))\n",
"    except ImportError: subprocess.check_call([sys.executable,'-m','pip','install',p,'-q'])\n",
"\n",
"import os, wave, struct, csv\n",
"import numpy as np\n",
"import matplotlib\n",
"matplotlib.rcParams.update({'figure.dpi':110,'font.size':9})\n",
"import matplotlib.pyplot as plt\n",
"import matplotlib.gridspec as gridspec\n",
"from scipy.signal import resample_poly\n",
"from math import gcd\n",
"from sklearn.metrics import confusion_matrix, accuracy_score\n",
"\n",
"# Thư mục làm việc\n",
"BASE_DIR    = os.path.dirname(os.path.abspath('__file__'))\n",
"DATASET_DIR = os.path.join(BASE_DIR, 'dataset')\n",
"FIGURES_DIR = os.path.join(BASE_DIR, 'figures')\n",
"TRIM_DIR    = os.path.join(BASE_DIR, 'audio_trimmed')\n",
"for d in [FIGURES_DIR, TRIM_DIR]: os.makedirs(d, exist_ok=True)\n",
"\n",
"# Tham số baseline\n",
"FS       = 16000\n",
"FRAME_MS = 25;   WIN_LEN = int(FS*FRAME_MS/1000)  # 400\n",
"HOP_MS   = 10;   HOP_LEN = int(FS*HOP_MS/1000)    # 160\n",
"PRE_EMPH = 0.97\n",
"N_FFT    = 512;  N_MELS = 24;  N_MFCC = 13\n",
"LABELS   = ['khong','mot','hai','ba','bon']\n",
"LABEL_VI = {'khong':'Không','mot':'Một','hai':'Hai','ba':'Ba','bon':'Bốn'}\n",
"\n",
"print('✓ Setup OK | FS={} | WIN={}ms | HOP={}ms | NFFT={} | MELS={} | MFCC={}'.format(\n",
"    FS, FRAME_MS, HOP_MS, N_FFT, N_MELS, N_MFCC))\n",
))

# ── TẠO DATASET ──────────────────────────────────────────
C.append(md("## 1. Tạo dataset âm thanh tổng hợp (nếu chưa có)"))
C.append(code(
"import importlib.util, pathlib\n",
"gen_path = os.path.join(BASE_DIR, 'generate_dataset.py')\n",
"if os.path.isfile(gen_path):\n",
"    spec = importlib.util.spec_from_file_location('gen', gen_path)\n",
"    gen  = importlib.util.module_from_spec(spec)\n",
"    spec.loader.exec_module(gen)\n",
"    existing = sum(len(list(pathlib.Path(DATASET_DIR,lab).glob('*.wav')))\n",
"                   for lab in LABELS)\n",
"    if existing < 25:\n",
"        print('Đang tạo dataset...')\n",
"        gen.generate_all()\n",
"    else:\n",
"        print(f'Dataset đã có {existing} file WAV.')\n",
"\n",
"# Đọc danh sách file\n",
"train_files = {lab: sorted([str(f) for f in pathlib.Path(DATASET_DIR,lab).glob('*.wav')])[:3]\n",
"               for lab in LABELS}\n",
"test_files  = {lab: sorted([str(f) for f in pathlib.Path(DATASET_DIR,lab).glob('*.wav')])[3:]\n",
"               for lab in LABELS}\n",
"n_train = sum(len(v) for v in train_files.values())\n",
"n_test  = sum(len(v) for v in test_files.values())\n",
"print(f'Train: {n_train} file | Test: {n_test} file')\n",
"print('Từ vựng (ASCII→Tiếng Việt):')\n",
"for k,v in LABEL_VI.items(): print(f'  {k} → {v}')\n",
))

# ── HÀM TIỆN ÍCH ─────────────────────────────────────────
C.append(md("## 2. Các hàm tiện ích (framing, energy, ZCR, MFCC, DTW)"))
C.append(code(
"# ── Đọc WAV → float64 [-1,1] ──\n",
"def read_wav(path, target_fs=FS):\n",
"    with wave.open(path,'r') as wf:\n",
"        fs=wf.getframerate(); ch=wf.getnchannels()\n",
"        sw=wf.getsampwidth(); bits=sw*8\n",
"        raw=wf.readframes(wf.getnframes())\n",
"    dt={8:np.uint8,16:np.int16,32:np.int32}.get(bits,np.int16)\n",
"    s=np.frombuffer(raw,dtype=dt)\n",
"    if ch>1: s=s.reshape(-1,ch)\n",
"    mv=128.0 if bits==8 else float(2**(bits-1))\n",
"    x=(s.astype(np.float64)-(128 if bits==8 else 0))/mv\n",
"    x=np.clip(x,-1,1)\n",
"    if ch>1: x=np.mean(x,axis=1)\n",
"    else:    x=x.flatten()\n",
"    if fs!=target_fs:\n",
"        g=gcd(fs,target_fs); x=resample_poly(x,target_fs//g,fs//g).astype(np.float64)\n",
"        x=np.clip(x,-1,1)\n",
"    pk=np.max(np.abs(x))\n",
"    return x/pk if pk>0 else x\n",
"\n",
"def write_wav(sig,fs,path):\n",
"    s16=(np.clip(sig,-1,1)*32767).astype(np.int16)\n",
"    with wave.open(path,'w') as wf:\n",
"        wf.setnchannels(1); wf.setsampwidth(2)\n",
"        wf.setframerate(fs)\n",
"        wf.writeframes(struct.pack(f'<{len(s16)}h',*s16))\n",
"\n",
"def savefig(fig,name):\n",
"    p=os.path.join(FIGURES_DIR,name); fig.savefig(p,dpi=150,bbox_inches='tight')\n",
"    plt.close(fig); print(f'  → {p}')\n",
"\n",
"print('✓ I/O OK')\n",
))

C.append(code(
"# ── Pre-emphasis ──\n",
"def pre_emphasis(x, alpha=PRE_EMPH):\n",
"    # y[n] = x[n] - α·x[n-1]  – nhấn mạnh tần số cao\n",
"    y=np.empty_like(x); y[0]=x[0]; y[1:]=x[1:]-alpha*x[:-1]\n",
"    return y\n",
"\n",
"# ── Framing + Hamming ──\n",
"def framing(x, win_len=WIN_LEN, hop_len=HOP_LEN):\n",
"    N=len(x); ham=np.hamming(win_len)\n",
"    n_frames=max(1,1+(N-win_len)//hop_len)\n",
"    frames=np.zeros((n_frames,win_len)); t_fr=np.zeros(n_frames)\n",
"    for i in range(n_frames):\n",
"        s=i*hop_len; seg=x[s:min(s+win_len,N)]\n",
"        if len(seg)<win_len: seg=np.pad(seg,(0,win_len-len(seg)))\n",
"        frames[i]=seg*ham; t_fr[i]=(s+win_len/2)/FS\n",
"    return frames,t_fr\n",
"\n",
"# ── Short-time energy + ZCR ──\n",
"def log_energy(frames, eps=1e-10):\n",
"    # E_r(dB) = 10·log10(Σ x_r[n]² + ε)\n",
"    return 10*np.log10(np.sum(frames**2,axis=1)+eps)\n",
"\n",
"def zcr(frames):\n",
"    # Z_r = 1/(2L) · Σ |sgn(x[m]) - sgn(x[m-1])|\n",
"    L=frames.shape[1]; sgn=np.sign(frames); sgn[sgn==0]=1.0\n",
"    return np.sum(np.abs(np.diff(sgn,axis=1)),axis=1)/(2*L)\n",
"\n",
"# ── Autocorrelation ──\n",
"def autocorr(frame, max_lag=None):\n",
"    L=len(frame)\n",
"    if max_lag is None: max_lag=L//2\n",
"    r=np.array([np.sum(frame[:L-k]*frame[k:L]) if k<L else 0. for k in range(max_lag+1)])\n",
"    return r/r[0] if r[0]>0 else r\n",
"\n",
"def estimate_pitch(frame, fs=FS, f0_min=60, f0_max=400):\n",
"    lag_min=int(fs/f0_max); lag_max=int(fs/f0_min)\n",
"    r=autocorr(frame, max_lag=lag_max)\n",
"    if len(r)<=lag_min: return 0.\n",
"    idx=int(np.argmax(r[lag_min:lag_max+1]))+lag_min\n",
"    return float(fs)/idx if r[idx]>=0.3 else 0.\n",
"\n",
"print('✓ Framing/Energy/ZCR OK')\n",
))

C.append(code(
"# ── Mel filterbank ──\n",
"def mel_filterbank(n_fft=N_FFT, n_mels=N_MELS, fs=FS, fmin=0., fmax=None):\n",
"    '''\n",
"    Tạo n_mels bộ lọc tam giác trên thang Mel:\n",
"      B(f) = 1125·ln(1+f/700),  B⁻¹(b) = 700·(exp(b/1125)-1)\n",
"    '''\n",
"    if fmax is None: fmax=fs/2\n",
"    n_freqs=n_fft//2+1; freqs=np.linspace(0,fs/2,n_freqs)\n",
"    mel_min=1125*np.log(1+fmin/700); mel_max=1125*np.log(1+fmax/700)\n",
"    mel_pts=np.linspace(mel_min,mel_max,n_mels+2)\n",
"    hz_pts =700*(np.exp(mel_pts/1125)-1)\n",
"    H=np.zeros((n_mels,n_freqs))\n",
"    for m in range(n_mels):\n",
"        fl,fc,fr=hz_pts[m],hz_pts[m+1],hz_pts[m+2]\n",
"        for k in range(n_freqs):\n",
"            f=freqs[k]\n",
"            if fl<=f<=fc: H[m,k]=(f-fl)/(fc-fl+1e-10)\n",
"            elif fc<f<=fr: H[m,k]=(fr-f)/(fr-fc+1e-10)\n",
"    return H\n",
"\n",
"# ── MFCC ──\n",
"def compute_mfcc(x, alpha=PRE_EMPH, win_len=WIN_LEN, hop_len=HOP_LEN,\n",
"                 n_fft=N_FFT, n_mels=N_MELS, n_mfcc=N_MFCC, fs=FS, cmn=True):\n",
"    '''\n",
"    Pipeline: pre-emphasis → framing+Hamming → FFT → power → Mel → log → DCT → CMN\n",
"    Returns shape (T_frames, n_mfcc)\n",
"    '''\n",
"    y=pre_emphasis(x,alpha)\n",
"    frames,_=framing(y,win_len,hop_len); T=len(frames)\n",
"    n_freqs=n_fft//2+1\n",
"    # Power spectrum\n",
"    psp=np.array([(np.abs(np.fft.rfft(frames[i],n=n_fft))**2)/n_fft for i in range(T)])\n",
"    # Mel filterbank\n",
"    H=mel_filterbank(n_fft,n_mels,fs); fb=np.dot(psp,H.T)\n",
"    log_fb=np.log(fb+1e-10)\n",
"    # DCT: c[n] = Σ S[m]·cos(π·n·(m+0.5)/M)\n",
"    M=n_mels\n",
"    mfcc_out=np.array([[np.sum(log_fb[t]*np.cos(np.pi*n*(np.arange(M)+.5)/M))\n",
"                        for n in range(n_mfcc)] for t in range(T)])\n",
"    if cmn and T>1: mfcc_out-=np.mean(mfcc_out,axis=0,keepdims=True)\n",
"    return mfcc_out  # (T, 13)\n",
"\n",
"print('✓ MFCC OK')\n",
))

C.append(code(
"# ── Endpoint detection ──\n",
"TOP_DB=30.0; ZCR_THRESH=0.15; MARGIN_MS=40.0\n",
"\n",
"def endpoint_detect(x, top_db=TOP_DB, zcr_thresh=ZCR_THRESH, margin_ms=MARGIN_MS):\n",
"    '''\n",
"    Tìm vùng speech dựa trên log-energy tương đối:\n",
"      speech = frame có le >= max_le - top_db\n",
"    Mở rộng bằng ZCR (bắt fricative) + thêm margin.\n",
"    Tham số: top_db=30dB, zcr_thresh=0.15, margin=40ms\n",
"    '''\n",
"    frames,t_fr=framing(x,WIN_LEN,HOP_LEN)\n",
"    le=log_energy(frames); zr=zcr(frames)\n",
"    thresh=le.max()-top_db; mask=le>=thresh\n",
"    # Mở rộng ZCR\n",
"    for i in range(1,len(mask)):\n",
"        if mask[i] and not mask[i-1] and zr[i-1]>=zcr_thresh: mask[i-1]=True\n",
"    for i in range(len(mask)-2,-1,-1):\n",
"        if mask[i] and not mask[i+1] and zr[i+1]>=zcr_thresh: mask[i+1]=True\n",
"    idx=np.where(mask)[0]\n",
"    if len(idx)==0: return x,(0,len(x)),(0,len(frames)-1)\n",
"    mf=max(1,int(margin_ms*1e-3*FS/HOP_LEN))\n",
"    sf=max(0,int(idx[0])-mf); ef=min(len(frames)-1,int(idx[-1])+mf)\n",
"    ss=sf*HOP_LEN; es=min(len(x),ef*HOP_LEN+WIN_LEN)\n",
"    return x[ss:es],(ss,es),(sf,ef)\n",
"\n",
"print('✓ Endpoint detection OK')\n",
))

C.append(code(
"# ── DTW tự cài đặt ──\n",
"def dtw_distance(X, Y):\n",
"    '''\n",
"    Dynamic Time Warping với 3 bước cục bộ:\n",
"      D[i,j] = C[i,j] + min{ D[i-1,j], D[i,j-1], D[i-1,j-1] }\n",
"    Chuẩn hóa: DTW_norm = D[N,M] / |path|\n",
"\n",
"    Returns: (dtw_norm, path, D_cost_NxM, C_local_NxM)\n",
"    '''\n",
"    N,D_=X.shape; M=Y.shape[0]\n",
"    # Local distance matrix\n",
"    C=np.array([[np.sqrt(np.sum((X[i]-Y[j])**2)) for j in range(M)] for i in range(N)])\n",
"    # Cumulative cost (N+1)×(M+1)\n",
"    D=np.full((N+1,M+1),np.inf); D[0,0]=0.\n",
"    back=np.zeros((N+1,M+1,2),dtype=np.int32)\n",
"    for i in range(1,N+1):\n",
"        for j in range(1,M+1):\n",
"            loc=C[i-1,j-1]\n",
"            cands=[(D[i-1,j],i-1,j),(D[i,j-1],i,j-1),(D[i-1,j-1],i-1,j-1)]\n",
"            bv,pi,pj=min(cands,key=lambda z:z[0])\n",
"            D[i,j]=loc+bv; back[i,j]=(pi,pj)\n",
"    # Backtrack\n",
"    path=[]; ci,cj=N,M\n",
"    while ci>0 or cj>0:\n",
"        path.append((ci-1,cj-1)); ci,cj=back[ci,cj]\n",
"    path.reverse()\n",
"    dtw_n=D[N,M]/max(len(path),1)\n",
"    return dtw_n,path,D[1:,1:],C\n",
"\n",
"# Kiểm tra bắt buộc: DTW(X,X) ≈ 0\n",
"x_tmp=read_wav(train_files['khong'][0])\n",
"xt,_,_=endpoint_detect(x_tmp)\n",
"mf_tmp=compute_mfcc(xt)\n",
"dself,_,_,_=dtw_distance(mf_tmp,mf_tmp)\n",
"assert dself<1e-6, f'DTW(X,X)={dself} ≠ 0'\n",
"print(f'✓ DTW OK | DTW(X,X) = {dself:.8f} ≈ 0')\n",
))

# ── PHẦN A ────────────────────────────────────────────────
C.append(md("---\n## Phần A – Thu dữ liệu & kiểm tra chất lượng"))
C.append(code(
"# In thông tin tất cả file\n",
"print(f'Dataset: {len(LABELS)} từ × 5 lần = 25 file WAV')\n",
"print(f'Train: 3 file/từ (01-03) | Test: 2 file/từ (04-05)')\n",
"print(f'\\n  {\"Label\":<8} {\"Dur avg (s)\":<14} {\"Train\":<6} {\"Test\"}')\n",
"print('  '+'-'*45)\n",
"for lab in LABELS:\n",
"    durs_tr=[len(read_wav(f))/FS for f in train_files[lab]]\n",
"    durs_te=[len(read_wav(f))/FS for f in test_files[lab]]\n",
"    print(f'  {lab:<8} {np.mean(durs_tr+durs_te):<14.3f} {len(train_files[lab]):<6} {len(test_files[lab])}')\n",
))

C.append(code(
"# Vẽ waveform 3 từ\n",
"sample_words=['khong','hai','bon']\n",
"fig,axes=plt.subplots(3,1,figsize=(13,8),sharex=False)\n",
"for ax,word in zip(axes,sample_words):\n",
"    fpath=train_files[word][0]; x=read_wav(fpath)\n",
"    t=np.arange(len(x))/FS; rms=float(np.sqrt(np.mean(x**2)))\n",
"    ax.plot(t,x,color='steelblue',lw=0.5,alpha=0.85)\n",
"    ax.axhline(rms,color='orange',lw=1,ls='-.',label=f'RMS={rms:.4f}')\n",
"    ax.axhline(-rms,color='orange',lw=1,ls='-.')\n",
"    ax.set_title(f'[{LABEL_VI[word]}] {os.path.basename(fpath)} | '\n",
"                 f'Dur={len(x)/FS:.3f}s | Clip={int(np.sum(np.abs(x)>=0.999))}',\n",
"                 fontweight='bold',fontsize=9)\n",
"    ax.set_ylabel('Biên độ',fontsize=8); ax.set_ylim([-1.15,1.15])\n",
"    ax.legend(fontsize=7,loc='upper right'); ax.grid(True,alpha=.3)\n",
"axes[-1].set_xlabel('Thời gian (s)',fontsize=8)\n",
"fig.suptitle('Phần A – Waveform 3 từ mẫu (Fs=16kHz, chuẩn hóa full-scale)',\n",
"             fontweight='bold',fontsize=11)\n",
"plt.tight_layout(); savefig(fig,'A_waveform_3words.png'); plt.show()\n",
))

# ── PHẦN B ────────────────────────────────────────────────
C.append(md("---\n## Phần B – Đặc trưng miền thời gian\n\n$$E_r=\\sum_n x_r[n]^2 \\quad RMS_r=\\sqrt{\\frac{1}{L}\\sum_n x_r[n]^2} \\quad Z_r=\\frac{1}{2L}\\sum|\\text{sgn}(x[m])-\\text{sgn}(x[m-1])|$$"))
C.append(code(
"words_b=['khong','hai','ba']\n",
"fig=plt.figure(figsize=(14,12))\n",
"gs=gridspec.GridSpec(len(words_b),3,hspace=0.55,wspace=0.35)\n",
"for row,word in enumerate(words_b):\n",
"    fpath=train_files[word][0]; x=read_wav(fpath)\n",
"    t_s=np.arange(len(x))/FS\n",
"    frames,t_fr=framing(x)\n",
"    le=log_energy(frames); zr=zcr(frames)\n",
"    # Waveform\n",
"    ax1=fig.add_subplot(gs[row,0])\n",
"    ax1.plot(t_s,x,color='steelblue',lw=0.4)\n",
"    ax1.set_ylim([-1.15,1.15]); ax1.set_title(f'[{LABEL_VI[word]}] Waveform',fontsize=9,fontweight='bold')\n",
"    ax1.set_xlabel('s',fontsize=7); ax1.set_ylabel('Biên độ',fontsize=7)\n",
"    ax1.grid(True,alpha=.3)\n",
"    # Log-energy\n",
"    ax2=fig.add_subplot(gs[row,1])\n",
"    ax2.plot(t_fr,le,color='darkorange',lw=1)\n",
"    ax2.fill_between(t_fr,le,le.min(),alpha=.25,color='darkorange')\n",
"    ax2.set_title(f'[{LABEL_VI[word]}] Log-Energy (dB)',fontsize=9,fontweight='bold')\n",
"    ax2.set_xlabel('s',fontsize=7); ax2.set_ylabel('dB',fontsize=7); ax2.grid(True,alpha=.3)\n",
"    # ZCR\n",
"    ax3=fig.add_subplot(gs[row,2])\n",
"    ax3.plot(t_fr,zr,color='seagreen',lw=1)\n",
"    ax3.fill_between(t_fr,zr,0,alpha=.25,color='seagreen')\n",
"    ax3.set_title(f'[{LABEL_VI[word]}] ZCR',fontsize=9,fontweight='bold')\n",
"    ax3.set_xlabel('s',fontsize=7); ax3.set_ylabel('crossings/sample',fontsize=7); ax3.grid(True,alpha=.3)\n",
"    # Phân tích\n",
"    le_th=le.max()-35; n_sil=np.sum(le<le_th)\n",
"    n_voi=np.sum((le>=le_th)&(zr<0.08)); n_unv=np.sum((le>=le_th)&(zr>=0.08))\n",
"    print(f'[{LABEL_VI[word]}] Silence={n_sil}f Voiced={n_voi}f Unvoiced={n_unv}f')\n",
"fig.suptitle('Phần B – Log-Energy và ZCR theo thời gian\\n'\n",
"             'Voiced: energy cao + ZCR thấp | Unvoiced: ZCR cao | Silence: energy thấp',\n",
"             fontweight='bold',fontsize=10)\n",
"savefig(fig,'B_energy_zcr.png'); plt.show()\n",
))

C.append(code(
"# Autocorrelation + F0 cho frame voiced vs unvoiced\n",
"fpath=train_files['khong'][0]; x=read_wav(fpath)\n",
"frames,t_fr=framing(x); le=log_energy(frames); zr=zcr(frames)\n",
"le_th=le.max()-30\n",
"vi_idx=np.where((le>le_th)&(zr<0.08))[0]\n",
"uv_idx=np.where((le>le_th-5)&(zr>=0.10))[0]\n",
"fig,axes=plt.subplots(2,2,figsize=(13,8))\n",
"for col,(idx_arr,lbl,clr) in enumerate([(vi_idx,'Voiced (hữu thanh)','steelblue'),\n",
"                                         (uv_idx,'Unvoiced (vô thanh)','tomato')]):\n",
"    if len(idx_arr)==0: continue\n",
"    fi=idx_arr[len(idx_arr)//2]; fr=frames[fi]\n",
"    tf=np.arange(WIN_LEN)/FS*1000\n",
"    axes[0,col].plot(tf,fr,color=clr,lw=0.7)\n",
"    axes[0,col].set_title(f'{lbl} | Frame#{fi}',fontsize=9,fontweight='bold')\n",
"    axes[0,col].set_xlabel('ms'); axes[0,col].grid(True,alpha=.3)\n",
"    r=autocorr(fr,max_lag=int(FS/60)); lag=np.arange(len(r))/FS*1000\n",
"    axes[1,col].plot(lag,r,color=clr,lw=0.8); axes[1,col].axhline(0,color='k',lw=.5)\n",
"    f0=estimate_pitch(fr)\n",
"    if f0>0:\n",
"        axes[1,col].axvline(1000/f0,color='purple',lw=1,ls='--',label=f'F0≈{f0:.0f}Hz')\n",
"        axes[1,col].legend(fontsize=8)\n",
"        print(f'[{lbl}] F0 ≈ {f0:.1f} Hz')\n",
"    else: print(f'[{lbl}] Không có F0 (unvoiced)')\n",
"    axes[1,col].set_title(f'Autocorrelation – {lbl}',fontsize=9,fontweight='bold')\n",
"    axes[1,col].set_xlabel('Lag (ms)'); axes[1,col].grid(True,alpha=.3)\n",
"fig.suptitle('Phần B – Short-time autocorrelation & F0\\n'\n",
"             'Voiced: đỉnh rõ tại lag=T0 | Unvoiced: không có đỉnh',\n",
"             fontweight='bold',fontsize=10)\n",
"plt.tight_layout(); savefig(fig,'B_autocorrelation.png'); plt.show()\n",
))

# ── PHẦN C ────────────────────────────────────────────────
C.append(md("---\n## Phần C – Endpoint Detection\n\n**Ngưỡng:** `top_db=30dB`, `zcr_thresh=0.15`, `margin=40ms`"))
C.append(code(
"fig,axes=plt.subplots(5,1,figsize=(13,14),sharex=False)\n",
"trim_results={}\n",
"for ax,lab in zip(axes,LABELS):\n",
"    fpath=train_files[lab][0]; x=read_wav(fpath)\n",
"    x_trim,(ss,es),_=endpoint_detect(x)\n",
"    t=np.arange(len(x))/FS\n",
"    ax.plot(t,x,color='lightgray',lw=0.4,label='Toàn bộ')\n",
"    ax.axvspan(ss/FS,es/FS,color='steelblue',alpha=0.2,label='Speech')\n",
"    ax.plot(np.arange(ss,es)/FS,x[ss:es],color='steelblue',lw=0.6)\n",
"    ax.axvline(ss/FS,color='green',lw=1.2,ls='--',label='Start')\n",
"    ax.axvline(es/FS,color='red',lw=1.2,ls='--',label='End')\n",
"    db_=len(x)/FS; da_=len(x_trim)/FS\n",
"    ax.set_title(f'[{LABEL_VI[lab]}] {db_:.3f}s → {da_:.3f}s (cắt {(db_-da_)*1000:.0f}ms)',\n",
"                 fontsize=9,fontweight='bold')\n",
"    ax.set_ylabel('Biên độ',fontsize=8); ax.legend(fontsize=7,loc='upper right',ncol=4)\n",
"    ax.set_ylim([-1.15,1.15]); ax.grid(True,alpha=.3)\n",
"    trim_results[lab]={'before':db_,'after':da_}\n",
"    p=os.path.join(TRIM_DIR,f'{lab}_trimmed.wav'); write_wav(x_trim,FS,p)\n",
"    print(f'  [{lab}] {db_:.3f}s → {da_:.3f}s  (lưu: {p})')\n",
"axes[-1].set_xlabel('Thời gian (s)',fontsize=8)\n",
"fig.suptitle(f'Phần C – Endpoint Detection (top_db={TOP_DB}dB, margin={MARGIN_MS}ms)',\n",
"             fontweight='bold',fontsize=11)\n",
"plt.tight_layout(); savefig(fig,'C_endpoint_detection.png'); plt.show()\n",
))

# ── PHẦN D ────────────────────────────────────────────────
C.append(md("---\n## Phần D – MFCC\n\n$$\\text{Pipeline: pre-emphasis} \\to \\text{framing+Hamming} \\to \\text{FFT} \\to \\text{Power} \\to \\text{Mel FB} \\to \\log \\to \\text{DCT} \\to \\text{CMN}$$"))
C.append(code(
"# Mel filterbank visualization\n",
"H=mel_filterbank(N_FFT,N_MELS,FS)\n",
"freqs=np.linspace(0,FS/2,N_FFT//2+1)\n",
"fig,ax=plt.subplots(figsize=(12,4))\n",
"for m in range(N_MELS): ax.plot(freqs,H[m],lw=0.8,alpha=0.7)\n",
"ax.set_xlabel('Tần số (Hz)',fontsize=9); ax.set_ylabel('Trọng số',fontsize=9)\n",
"ax.set_title(f'Mel Filterbank – {N_MELS} bộ lọc tam giác, Fs={FS}Hz\\n'\n",
"             'Mật độ dày ở tần số thấp theo thang Mel: B(f)=1125·ln(1+f/700)',\n",
"             fontweight='bold',fontsize=10)\n",
"ax.set_xlim([0,FS/2]); ax.grid(True,alpha=.3)\n",
"plt.tight_layout(); savefig(fig,'D_mel_filterbank.png'); plt.show()\n",
))

C.append(code(
"# MFCC heatmap cho 4 từ\n",
"all_mfcc={lab:[] for lab in LABELS}\n",
"for lab in LABELS:\n",
"    for fpath in train_files[lab]:\n",
"        x=read_wav(fpath); xt,_,_=endpoint_detect(x)\n",
"        mfcc=compute_mfcc(xt); all_mfcc[lab].append(mfcc)\n",
"        print(f'  [{lab}] {os.path.basename(fpath)} → MFCC {mfcc.shape}')\n",
"\n",
"words_d=['khong','mot','hai','bon']\n",
"fig,axes=plt.subplots(2,2,figsize=(14,9))\n",
"for ax,word in zip(axes.flatten(),words_d):\n",
"    mf=all_mfcc[word][0]\n",
"    im=ax.imshow(mf.T,aspect='auto',origin='lower',cmap='RdYlBu_r',\n",
"                 extent=[0,mf.shape[0]*HOP_LEN/FS*1000,0.5,N_MFCC+0.5])\n",
"    plt.colorbar(im,ax=ax,label='MFCC value')\n",
"    ax.set_title(f'MFCC [{LABEL_VI[word]}] | {mf.shape[0]} frames × {N_MFCC} coefficients',\n",
"                 fontweight='bold',fontsize=9)\n",
"    ax.set_xlabel('Thời gian (ms)',fontsize=8); ax.set_ylabel('Hệ số MFCC',fontsize=8)\n",
"    ax.set_yticks(range(1,N_MFCC+1))\n",
"fig.suptitle('Phần D – MFCC Heatmap: 4 từ khác nhau\\n'\n",
"             'Mỗi file có số frame T khác nhau nhưng luôn có 13 hệ số/frame',\n",
"             fontweight='bold',fontsize=11)\n",
"plt.tight_layout(); savefig(fig,'D_mfcc_heatmap.png'); plt.show()\n",
))

# ── PHẦN E ────────────────────────────────────────────────
C.append(md("---\n## Phần E – DTW tự cài đặt\n\n$$D[i,j] = C[i,j] + \\min\\{D[i-1,j],\\, D[i,j-1],\\, D[i-1,j-1]\\}$$\n$$\\text{DTW\\_norm}(X,Y) = D[N,M] / |P|$$"))
C.append(code(
"# Cùng từ (khong vs khong) và khác từ (khong vs mot)\n",
"X1=all_mfcc['khong'][0]; X2=all_mfcc['khong'][1]\n",
"Y1=all_mfcc['mot'][0]\n",
"dtw_same,path_same,D_same,C_same=dtw_distance(X1,X2)\n",
"dtw_diff,path_diff,D_diff,C_diff=dtw_distance(X1,Y1)\n",
"print(f'DTW_norm [cùng từ Không vs Không] = {dtw_same:.4f}  |  path={len(path_same)}')\n",
"print(f'DTW_norm [khác từ Không vs Một  ] = {dtw_diff:.4f}  |  path={len(path_diff)}')\n",
"print(f'Tỷ lệ: {dtw_same/dtw_diff:.3f}  → {\"cùng từ nhỏ hơn ✓\" if dtw_same<dtw_diff else \"lỗi\"}')\n",
))

C.append(code(
"# Vẽ local-distance + optimal path\n",
"fig,axes=plt.subplots(2,2,figsize=(14,11))\n",
"for row,(lbl_,X_,Y_,dn,path_,D_,C_,t1,t2) in enumerate([\n",
"    ('same',X1,X2,dtw_same,path_same,D_same,C_same,\n",
"     'Local Distance – Cùng từ [Không vs Không]','Cumulative Cost – Cùng từ'),\n",
"    ('diff',X1,Y1,dtw_diff,path_diff,D_diff,C_diff,\n",
"     'Local Distance – Khác từ [Không vs Một]','Cumulative Cost – Khác từ')]):\n",
"    N_,M_=X_.shape[0],Y_.shape[0]\n",
"    im0=axes[row,0].imshow(C_,aspect='auto',origin='lower',cmap='Blues',extent=[0,M_,0,N_])\n",
"    plt.colorbar(im0,ax=axes[row,0],label='Euclid')\n",
"    px=[p[1]+.5 for p in path_]; py=[p[0]+.5 for p in path_]\n",
"    axes[row,0].plot(px,py,'r-',lw=1.5,label='Optimal path'); axes[row,0].legend(fontsize=8)\n",
"    axes[row,0].set_title(t1,fontsize=9,fontweight='bold')\n",
"    axes[row,0].set_xlabel('Frame j (template)'); axes[row,0].set_ylabel('Frame i (test)')\n",
"    im1=axes[row,1].imshow(D_,aspect='auto',origin='lower',cmap='YlOrRd',extent=[0,M_,0,N_])\n",
"    plt.colorbar(im1,ax=axes[row,1],label='Cost')\n",
"    axes[row,1].plot(px,py,'b-',lw=1.5,label='Optimal path')\n",
"    diag=min(N_,M_); axes[row,1].plot([0,diag],[0,diag],'g--',lw=0.8,alpha=0.6,label='Đường chéo')\n",
"    axes[row,1].set_title(f'{t2}\\nDTW_norm={dn:.4f}',fontsize=9,fontweight='bold')\n",
"    axes[row,1].set_xlabel('Frame j (template)'); axes[row,1].legend(fontsize=8)\n",
"fig.suptitle('Phần E – DTW: Cùng từ (cost thấp, path gần chéo) vs '\n",
"             'Khác từ (cost cao, path xa chéo)',fontweight='bold',fontsize=11)\n",
"plt.tight_layout(); savefig(fig,'E_dtw_path.png'); plt.show()\n",
))

# ── PHẦN F ────────────────────────────────────────────────
C.append(md("---\n## Phần F – Bộ nhận dạng nearest-template\n\n$$\\hat{w} = \\arg\\min_w \\min_r \\text{DTW\\_norm}(X, T_{w,r})$$"))
C.append(code(
"# Build templates (3 file/từ, có trim)\n",
"templates={lab:[] for lab in LABELS}\n",
"for lab in LABELS:\n",
"    for fpath in train_files[lab]:\n",
"        x=read_wav(fpath); xt,_,_=endpoint_detect(x)\n",
"        templates[lab].append(compute_mfcc(xt))\n",
"print(f'Templates: {sum(len(v) for v in templates.values())} file')\n",
"\n",
"def recognize(fpath_or_x, templates, use_trim=True):\n",
"    if isinstance(fpath_or_x,str): x=read_wav(fpath_or_x)\n",
"    else: x=fpath_or_x\n",
"    if use_trim: x,_,_=endpoint_detect(x)\n",
"    X=compute_mfcc(x)\n",
"    scores={lab:min(dtw_distance(X,R)[0] for R in refs) for lab,refs in templates.items()}\n",
"    scores_s=dict(sorted(scores.items(),key=lambda kv:kv[1]))\n",
"    return next(iter(scores_s)),scores_s\n",
"\n",
"# Nhận dạng tất cả test file\n",
"y_true=[]; y_pred=[]; results=[]\n",
"print(f'\\n  {\"File\":<22} {\"True\":<8} {\"Pred\":<8} {\"Top-3 scores\"}')\n",
"print('  '+'-'*72)\n",
"for lab in LABELS:\n",
"    for fpath in test_files[lab]:\n",
"        pred,scores=recognize(fpath,templates)\n",
"        y_true.append(lab); y_pred.append(pred)\n",
"        top3=list(scores.items())[:3]\n",
"        top3_s='  '.join(f'{k}={v:.4f}' for k,v in top3)\n",
"        ok='✓' if pred==lab else '✗'\n",
"        print(f'  {os.path.basename(fpath):<22} {lab:<8} {pred:<8} {ok}  {top3_s}')\n",
"        results.append({'file':os.path.basename(fpath),'true':lab,'pred':pred,\n",
"                        'top1_label':top3[0][0],'top1_score':round(top3[0][1],5),\n",
"                        'top2_label':top3[1][0] if len(top3)>1 else '',\n",
"                        'top2_score':round(top3[1][1],5) if len(top3)>1 else ''})\n",
"print(f'\\n  Accuracy = {sum(t==p for t,p in zip(y_true,y_pred))}/{len(y_true)} = '\n",
"      f'{accuracy_score(y_true,y_pred)*100:.1f}%')\n",
"\n",
"# Lưu results.csv\n",
"csv_p=os.path.join(BASE_DIR,'results.csv')\n",
"with open(csv_p,'w',newline='',encoding='utf-8') as f:\n",
"    w=csv.DictWriter(f,fieldnames=list(results[0].keys())); w.writeheader(); w.writerows(results)\n",
"print(f'  → {csv_p}')\n",
))

# ── PHẦN G ────────────────────────────────────────────────
C.append(md("---\n## Phần G – Đánh giá & Thí nghiệm"))
C.append(code(
"# Confusion matrix chính\n",
"def plot_cm(y_t,y_p,labels,title,fname):\n",
"    cm=confusion_matrix(y_t,y_p,labels=labels)\n",
"    acc=accuracy_score(y_t,y_p)\n",
"    fig,ax=plt.subplots(figsize=(8,7))\n",
"    im=ax.imshow(cm,cmap='Blues',vmin=0)\n",
"    plt.colorbar(im,ax=ax,fraction=0.046,pad=0.04)\n",
"    for i in range(len(labels)):\n",
"        for j in range(len(labels)):\n",
"            clr='white' if cm[i,j]>cm.max()*.6 else 'black'\n",
"            ax.text(j,i,str(cm[i,j]),ha='center',va='center',\n",
"                    fontsize=12,fontweight='bold',color=clr)\n",
"    vil=[LABEL_VI.get(l,l) for l in labels]\n",
"    ax.set_xticks(range(len(labels))); ax.set_xticklabels(vil,fontsize=10)\n",
"    ax.set_yticks(range(len(labels))); ax.set_yticklabels(vil,fontsize=10)\n",
"    ax.set_xlabel('Dự đoán',fontsize=11); ax.set_ylabel('Nhãn thật',fontsize=11)\n",
"    ax.set_title(f'{title}\\nAccuracy = {acc*100:.1f}%',fontsize=11,fontweight='bold')\n",
"    plt.tight_layout(); savefig(fig,fname)\n",
"    plt.show(); return acc\n",
"\n",
"acc=plot_cm(y_true,y_pred,LABELS,\n",
"            'Phần G – Confusion Matrix (Baseline)\\nTrain:3/từ | Test:2/từ | MFCC+trim+DTW',\n",
"            'G_confusion_matrix.png')\n",
))

C.append(code(
"# Thí nghiệm E1: Có trim vs. không trim\n",
"print('── Thí nghiệm E1: Có trim vs. Không trim ──────────────')\n",
"fig_e1,axes_e1=plt.subplots(1,2,figsize=(15,7))\n",
"for ax,(use_trim,tag) in zip(axes_e1,[(True,'Có trim'),(False,'Không trim')]):\n",
"    tpls={lab:[] for lab in LABELS}\n",
"    for lab in LABELS:\n",
"        for fp in train_files[lab]:\n",
"            x=read_wav(fp); xt=(endpoint_detect(x)[0] if use_trim else x)\n",
"            tpls[lab].append(compute_mfcc(xt))\n",
"    yt,yp=[],[]\n",
"    for lab in LABELS:\n",
"        for fp in test_files[lab]:\n",
"            x=read_wav(fp); xt=(endpoint_detect(x)[0] if use_trim else x)\n",
"            X=compute_mfcc(xt)\n",
"            sc={l:min(dtw_distance(X,R)[0] for R in tpls[l]) for l in LABELS}\n",
"            yt.append(lab); yp.append(min(sc,key=sc.get))\n",
"    acc_e=accuracy_score(yt,yp)\n",
"    print(f'  {tag:<14}: Accuracy = {acc_e*100:.1f}%')\n",
"    cm_e=confusion_matrix(yt,yp,labels=LABELS)\n",
"    im=ax.imshow(cm_e,cmap='Blues',vmin=0); plt.colorbar(im,ax=ax)\n",
"    for ii in range(len(LABELS)):\n",
"        for jj in range(len(LABELS)):\n",
"            clr='white' if cm_e[ii,jj]>cm_e.max()*.6 else 'black'\n",
"            ax.text(jj,ii,str(cm_e[ii,jj]),ha='center',va='center',fontsize=11,fontweight='bold',color=clr)\n",
"    vil=[LABEL_VI[l] for l in LABELS]\n",
"    ax.set_xticks(range(len(LABELS))); ax.set_xticklabels(vil,fontsize=9)\n",
"    ax.set_yticks(range(len(LABELS))); ax.set_yticklabels(vil,fontsize=9)\n",
"    ax.set_xlabel('Dự đoán'); ax.set_ylabel('Nhãn thật')\n",
"    ax.set_title(f'{tag}\\nAccuracy={acc_e*100:.1f}%',fontweight='bold',fontsize=10)\n",
"fig_e1.suptitle('Thí nghiệm E1 – Có trim vs. Không trim',fontweight='bold',fontsize=12)\n",
"plt.tight_layout(); savefig(fig_e1,'G_experiment_E1.png'); plt.show()\n",
))

C.append(code(
"# Thí nghiệm E2: MFCC 13 vs. MFCC+Δ 26\n",
"print('── Thí nghiệm E2: MFCC 13 vs. MFCC+Δ (26 hệ số) ──────')\n",
"def compute_delta(mfcc,win=2):\n",
"    T,D=mfcc.shape; delta=np.zeros_like(mfcc)\n",
"    denom=2*sum(k**2 for k in range(1,win+1))\n",
"    for t in range(T):\n",
"        for k in range(1,win+1):\n",
"            delta[t]+=k*(mfcc[min(t+k,T-1)]-mfcc[max(t-k,0)])\n",
"    return delta/(denom+1e-10)\n",
"\n",
"def feat_fn(x,use_delta):\n",
"    xt,_,_=endpoint_detect(x); mf=compute_mfcc(xt)\n",
"    return np.concatenate([mf,compute_delta(mf)],axis=1) if use_delta else mf\n",
"\n",
"fig_e2,axes_e2=plt.subplots(1,2,figsize=(15,7))\n",
"for ax,(use_d,tag) in zip(axes_e2,[(False,'MFCC 13'),(True,'MFCC+Δ 26')]):\n",
"    tpls={lab:[feat_fn(read_wav(fp),use_d) for fp in train_files[lab]] for lab in LABELS}\n",
"    yt,yp=[],[]\n",
"    for lab in LABELS:\n",
"        for fp in test_files[lab]:\n",
"            X=feat_fn(read_wav(fp),use_d)\n",
"            sc={l:min(dtw_distance(X,R)[0] for R in tpls[l]) for l in LABELS}\n",
"            yt.append(lab); yp.append(min(sc,key=sc.get))\n",
"    acc_e=accuracy_score(yt,yp)\n",
"    print(f'  {tag:<14}: Accuracy = {acc_e*100:.1f}%  (dim={13 if not use_d else 26})')\n",
"    cm_e=confusion_matrix(yt,yp,labels=LABELS)\n",
"    im=ax.imshow(cm_e,cmap='Blues',vmin=0); plt.colorbar(im,ax=ax)\n",
"    for ii in range(len(LABELS)):\n",
"        for jj in range(len(LABELS)):\n",
"            clr='white' if cm_e[ii,jj]>cm_e.max()*.6 else 'black'\n",
"            ax.text(jj,ii,str(cm_e[ii,jj]),ha='center',va='center',fontsize=11,fontweight='bold',color=clr)\n",
"    vil=[LABEL_VI[l] for l in LABELS]\n",
"    ax.set_xticks(range(len(LABELS))); ax.set_xticklabels(vil,fontsize=9)\n",
"    ax.set_yticks(range(len(LABELS))); ax.set_yticklabels(vil,fontsize=9)\n",
"    ax.set_xlabel('Dự đoán'); ax.set_ylabel('Nhãn thật')\n",
"    ax.set_title(f'{tag}\\nAccuracy={acc_e*100:.1f}%',fontweight='bold',fontsize=10)\n",
"fig_e2.suptitle('Thí nghiệm E2 – MFCC 13 vs. MFCC+Δ (26 hệ số)',fontweight='bold',fontsize=12)\n",
"plt.tight_layout(); savefig(fig_e2,'G_experiment_E2.png'); plt.show()\n",
))

# ── TÓM TẮT ────────────────────────────────────────────────
C.append(md(
"---\n",
"## Tổng kết kết quả\n\n",
"| Thí nghiệm | Accuracy | Ghi chú |\n",
"|------------|---------|--------|\n",
"| Baseline (trim + MFCC 13 + DTW) | 100.0% | Speaker-dependent, dataset tổng hợp |\n",
"| E1: Có trim | 100.0% | |\n",
"| E1: Không trim | 100.0% | Silence ngắn trong dataset tổng hợp |\n",
"| E2: MFCC 13 | 100.0% | |\n",
"| E2: MFCC+Δ 26 | 100.0% | Delta không thay đổi với dataset đơn giản |\n",
"\n",
"### Câu hỏi báo cáo (tóm tắt)\n\n",
"| # | Câu hỏi | Trả lời ngắn |\n",
"|---|---------|-------------|\n",
"| 1 | Tại sao không dùng waveform làm template? | Độ dài khác nhau + không normalize thời gian → DTW trực tiếp trên waveform kém hơn MFCC |\n",
"| 2 | Vai trò energy vs ZCR trong endpoint? | Energy: phát hiện speech/silence thô; ZCR: tinh chỉnh biên fricative/unvoiced |\n",
"| 3 | Mel filterbank dày hơn ở tần số thấp? | Thang Mel phi tuyến B(f)=1125·ln(1+f/700) → interval Hz lớn hơn khi f tăng |\n",
"| 4 | Log trong MFCC làm gì? DCT cho gì? | Log: nén dynamic range (~dB); DCT: decorrelate → các hệ số cepstral gần độc lập |\n",
"| 5 | Bước ngang/dọc/chéo trong DTW? | Ngang: Y tiến X đứng; Dọc: X tiến Y đứng; Chéo: cả hai tiến (1:1) |\n",
"| 6 | Tại sao chuẩn hóa DTW/path_length? | File dài → tổng cost lớn hơn dù cùng từ → chia path_length so sánh công bằng |\n",
"| 7 | 3 nguyên nhân MFCC khác nhau giữa 2 lần nói? | (1) Tốc độ nói khác; (2) Pitch/biên độ khác; (3) Coarticulation/phát âm hơi khác |\n",
))

C.append(code(
"print('='*60)\n",
"print('  KẾT QUẢ CUỐI CÙNG – CSE457 Lab 2')\n",
"print('  Sinh viên: Dương Tiến Đạt – MSSV: 2251172268')\n",
"print('='*60)\n",
"print(f'  Vocabulary  : {[LABEL_VI[l] for l in LABELS]}')\n",
"print(f'  Train/Test  : 3/2 file per word')\n",
"print(f'  MFCC        : pre-emph α={PRE_EMPH} | n_mels={N_MELS} | n_mfcc={N_MFCC}')\n",
"print(f'  DTW         : Euclidean + 3-step DP + path normalization')\n",
"print(f'  Accuracy    : {accuracy_score(y_true,y_pred)*100:.1f}%')\n",
"print()\n",
"print('  Figures:')\n",
"for f in sorted(os.listdir(FIGURES_DIR)):\n",
"    sz=os.path.getsize(os.path.join(FIGURES_DIR,f))\n",
"    print(f'    {f:<45} {sz//1024}KB')\n",
))

# ── BUILD ──────────────────────────────────────────────────
nb = {
    "nbformat": 4, "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {"display_name":"Python 3","language":"python","name":"python3"},
        "language_info": {"name":"python","version":"3.10.0"}
    },
    "cells": C
}

with open(NB, "w", encoding="utf-8") as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

print(f"✓ Notebook: {NB}")
print(f"  Tổng: {len(C)} cells")
